<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0-windows</TargetFramework>
        <UseWPF>true</UseWPF>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <RootNamespace>AFK_Assist</RootNamespace>
        <AssemblyName>AFK Assist</AssemblyName>
    </PropertyGroup>
    <PropertyGroup>
        <Product>AFK Assist</Product>
        <Company>AFK Assist</Company>
        <Description>Keeps A Game Active While You Are Away By Simulating Keyboard And Mouse Input</Description>
        <Copyright>Copyright 2026</Copyright>
        <Version>1.0.0</Version>
        <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    </PropertyGroup>
    <PropertyGroup>
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
        <SelfContained>true</SelfContained>
        <PublishSingleFile>true</PublishSingleFile>
        <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
        <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
        <DebugType>none</DebugType>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
        <PackageReference Include="WPF-UI" Version="4.3.0" />
    </ItemGroup>
</Project>
